(self.AMP=self.AMP||[]).push({n:"amp-auto-ads",v:"1811202351440",f:(function(AMP,_){
var h,ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},k;if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var m;a:{var ca={a:!0},p={};try{p.__proto__=ca;m=p.a;break a}catch(a){}m=!1}k=m?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=k;function da(a){return a?{top:a.top,bottom:a.bottom,left:a.left,right:a.right}:a};function ea(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b}function fa(a){return new Promise(function(b){b(a())})};function t(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ga=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;var ha=Object.prototype.toString;self.log=self.log||{user:null,dev:null,userForEmbed:null};var v=self.log;function w(){if(!v.user)throw Error("failed to call initLogConstructor");return v.user};function x(a,b){a=a.__AMP_TOP||a;return y(a,b)}function z(a){var b=A(a);b=B(b);return y(b,"documentInfo")}function C(a,b){a=A(a);a=B(a);return y(a,b)}function A(a){return a.nodeType?x((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function B(a){a=A(a);return a.isSingleDoc()?a.win:a}function y(a,b){var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var D=Object.prototype.hasOwnProperty;function E(a){return a||{}};function F(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function G(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};function H(a,b,c){a=a.createElement(b);for(var d in c)a.setAttribute(d,c[d]);return a}function ia(a,b){for(var c,d=a;d&&d!==c;d=d.parentElement)if(b(d))return d;return null}function ja(a,b){if(a.closest)return a.closest(b);b=b.toUpperCase();return ia(a,function(a){return a.tagName==b})}var I;
function ka(a,b){if(null==I){var c=a.ownerDocument;try{var d=c.createElement("div"),e=c.createElement("div");d.appendChild(e);I=d.querySelector(":scope div")===e}catch(f){I=!1}}if(I)return a.querySelectorAll(":scope "+b);a.classList.add("i-amphtml-scoped");b=a.querySelectorAll(".i-amphtml-scoped "+b);a.classList.remove("i-amphtml-scoped");return b}
function la(a){G(a.tagName,"AMP-");if(a.createdCallback)return Promise.resolve(a);if(!a.__AMP_UPG_PRM){var b=new ea;a.__AMP_UPG_PRM=b.promise;a.__AMP_UPG_RES=b.resolve}return a.__AMP_UPG_PRM};function K(a){return C(a,"viewport")};var ma={type:!0};function L(a){if(!a.attributes)return{};if("[object Object]"!==ha.call(a.attributes)||Array.isArray(a.attributes))return w().warn("amp-auto-ads","attributes property not an object"),{};var b=a.attributes,c={},d;for(d in b)if(ma[d]||G(d,"data-")){var e=typeof b[d];"number"!=e&&"string"!=e&&"boolean"!=e?w().warn("amp-auto-ads","Attribute type not supported: "+e):c[d]=String(b[d])}else w().warn("amp-auto-ads","Attribute not whitlisted: "+d);return c};var na=["AMP-SIDEBAR","AMP-APP-BANNER"],oa={1:function(a,b){a.parentNode.insertBefore(b,a)},4:function(a,b){a.parentNode.insertBefore(b,a.nextSibling)},2:function(a,b){a.insertBefore(b,a.firstChild)},3:function(a,b){a.appendChild(b)}};function M(a,b,c,d,e,f,g){this.ampdoc=a;this.C=b;this.l=c;this.T=d;this.P=e;this.K=f;this.H=g;this.F=null;this.j=0}M.prototype.getAdElement=function(){return this.F};
M.prototype.getEstimatedPosition=function(){var a=this;return this.C.getElementLayoutBox(this.l).then(function(b){a:{var c=b;switch(a.T){case 1:case 2:c=c.top;break a;case 3:case 4:c=c.bottom;break a;default:throw Error("Unknown position");}}return c})};
M.prototype.placeAd=function(a,b,c,d){var e=this;return this.getEstimatedPosition().then(function(f){return c.isTooNearAnAd(f).then(function(c){if(c)return e.j=3,e.j;e.F=pa(e,a,b.width);e.P(e.l,e.getAdElement());return qa(e,b,d).then(function(a){return la(e.getAdElement()).then(function(){return e.getAdElement().whenBuilt()}).then(function(){return e.C.attemptChangeSize(e.getAdElement(),a.height,a.width,a.margins)}).then(function(){e.j=2;return e.j},function(){e.j=1;return e.j})})})})};
function qa(a,b,c){var d=a.C.getViewport(),e=d.getWidth();if(c&&1200>=e){var f=d.getHeight(),g=ra(e,f),l=da(a.H);return C(a.l,"resources").getElementLayoutBox(a.l).then(function(b){var c;(c=a.ampdoc.win.getComputedStyle(a.l))||(c=Object.create(null));c=c.direction;0!==b.left&&(l=l||{},"rtl"==c?l.right=b.left:l.left=-b.left)}).then(function(){return Promise.resolve({width:e,height:g,margins:l})})}return Promise.resolve({height:b.height||250,margins:a.H})}
function pa(a,b,c){b=Object.assign(E({layout:c?"fixed":"fixed-height",height:"0",width:c?c:"auto","class":"i-amphtml-layout-awaiting-size"}),b,a.K);return H(a.ampdoc.win.document,"amp-ad",b)}function sa(a,b){var c=b.placements;if(!c)return w().info("amp-auto-ads","No placements in config"),[];var d=[];c.forEach(function(b){ta(a,b,d)});return d}
function ta(a,b,c){var d=oa[b.pos];if(d){var e=b.anchor;if(e){var f=N(a.getRootNode(),e);if(f.length){var g=void 0;if(b.style){var l=parseInt(b.style.top_m,10),u=parseInt(b.style.bot_m,10);if(l||u)g={top:l||void 0,bottom:u||void 0}}f.forEach(function(e){if(ua(e,b.pos)){var f=L(b);c.push(new M(a,C(e,"resources"),e,b.pos,d,f,g))}})}else w().warn("amp-auto-ads","No anchor element found")}else w().warn("amp-auto-ads","No anchor in placement")}else w().warn("amp-auto-ads","No injector for position")}
function N(a,b){var c=b.selector;if(!c)return w().warn("amp-auto-ads","No selector in anchor"),[];c=[].slice.call(ka(a.documentElement||a,c));var d=b.min_c||0;0<d&&(c=c.filter(function(a){return a.textContent.length>=d}));"number"!=typeof b.index&&b.all||(c=(c=c[b.index||0])?[c]:[]);if(0==c.length)return[];if(b.sub){var e=[];c.forEach(function(a){e=e.concat(N(a,b.sub))});return e}return c}
function ua(a,b){var c=1==b||4==b?a.parentElement:a;if(!c)return w().warn("amp-auto-ads","Parentless anchor with BEFORE/AFTER position."),!1;var d=c;return!na.some(function(a){return ja(d,a)?(w().warn("amp-auto-ads","Placement inside blacklisted ancestor: "+a),!0):!1})}function ra(a,b){var c=100,d=Math.min(300,b),e=Math.round(a/1.2);return Math.min(Math.max(e,c),d)};function O(){var a=100;this.M=a;this.A=this.D=0;this.w=Object.create(null)}O.prototype.has=function(a){return!!this.w[a]};O.prototype.get=function(a){var b=this.w[a];if(b)return b.access=++this.A,b.payload};
O.prototype.put=function(a,b){this.has(a)||this.D++;this.w[a]={payload:b,access:this.A};if(!(this.D<=this.M)){if(v.dev)a=v.dev;else throw Error("failed to call initLogConstructor");a.warn("lru-cache","Trimming LRU cache");a=this.w;var c=this.A+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.D--)}};E({c:!0,v:!0,a:!0,ad:!0});var P,Q;
function R(a){var b;P||(P=self.document.createElement("a"),Q=self.UrlCache||(self.UrlCache=new O));var c=b?null:Q,d=P;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=
d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;c&&c.put(a,e);a=e}return a};function S(a,b){if(a.__AMP__EXPERIMENT_TOGGLES)var c=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);c=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var d in a.AMP_CONFIG){var e=a.AMP_CONFIG[d];"number"===typeof e&&0<=e&&1>=e&&(c[d]=Math.random()<e)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(d=a.AMP_CONFIG["allow-doc-opt-in"],e=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){e=
e.getAttribute("content").split(",");for(var f=0;f<e.length;f++)-1!=d.indexOf(e[f])&&(c[e[f]]=!0)}Object.assign(c,va(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){d=a.AMP_CONFIG["allow-url-opt-in"];e=a.location.originalHash||a.location.hash;a=Object.create(null);if(e)for(var g;g=ga.exec(e);)f=t(g[1],g[1]),g=g[2]?t(g[2],g[2]):"",a[f]=g;for(e=0;e<d.length;e++)f=a["e-"+d[e]],"1"==f&&(c[d[e]]=!0),"0"==f&&(c[d[e]]=!1)}}var l=c;return!!l[b]}
function va(a){a:{try{var b=a.document.cookie}catch(g){b=""}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var c=a[b].trim(),d=c.indexOf("=");if(-1!=d&&"AMP_EXP"==t(c.substring(0,d).trim(),void 0)){a=c.substring(d+1).trim();a=t(a,a);break a}}a=null}var e=a,f=e?e.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<f.length;b++)0!=f[b].length&&("-"==f[b][0]?a[f[b].substr(1)]=!1:a[f[b]]=!0);return a}
function T(a,b){a.experimentBranches=a.experimentBranches||{};var c={},d;for(d in b)if(D.call(b,d))if(D.call(a.experimentBranches,d))c[d]=a.experimentBranches[d];else if(!b[d].isTrafficEligible||!b[d].isTrafficEligible(a))a.experimentBranches[d]=null;else if(!a.experimentBranches[d]&&S(a,d)){var e=b[d].branches,f=e;a.experimentBranches[d]=f[Math.floor(Math.random()*f.length)]||null;c[d]=a.experimentBranches[d]}};var wa={isTrafficEligible:function(a){return!!a.document.querySelector("AMP-AUTO-ADS")},branches:["3782001","3782002"]};var xa={isTrafficEligible:function(a){return!!a.document.querySelector("AMP-AUTO-ADS")},branches:["19861210","19861211"]};function U(a){var b=4096,c,d=[],e=c&&null!=c.value&&""!==c.value?encodeURIComponent(c.name)+"="+encodeURIComponent(String(c.value)):null,f=b-45;e&&(f-=e.length+1);for(var g=Object.keys(a),l=0;l<g.length;l++){var u=g[l],J=a[u];if(null!=J&&""!==J){var q=encodeURIComponent(u)+"=",n=encodeURIComponent(String(J)),Z=q.length+n.length+1;if(Z>f){var aa=n.substr(0,f-q.length-1).replace(/%\w?$/,"");aa&&d.push(q+aa);e&&d.push(e);break}d.push(q+n);f-=Z}}return d.length?"//pagead2.googlesyndication.com/getconfig/ama?"+
d.join("&"):"//pagead2.googlesyndication.com/getconfig/ama"};function ya(a,b){return"adsense"==a?new za(b):"doubleclick"==a?new Aa(b):null}function za(a){this.h=a}h=za.prototype;h.isEnabled=function(a){T(a,{"amp-auto-ads-adsense-holdout":wa});var b=(a.experimentBranches?a.experimentBranches["amp-auto-ads-adsense-holdout"]:null)||null;return"3782001"!=b};h.isResponsiveEnabled=function(a){T(a,{"amp-auto-ads-adsense-responsive":xa});return"19861210"!=((a.experimentBranches?a.experimentBranches["amp-auto-ads-adsense-responsive"]:null)||null)};
h.getConfigUrl=function(){var a=z(this.h).get(),b=R(a.canonicalUrl).hostname;return U({client:this.h.getAttribute("data-ad-client"),plah:b,ama_t:"amp",url:a.canonicalUrl})};h.getAttributes=function(){return E({type:"adsense","data-ad-client":this.h.getAttribute("data-ad-client")})};h.getDefaultAdConstraints=function(){var a=K(this.h).getSize().height;return{initialMinSpacing:a,subsequentMinSpacing:[{adCount:3,spacing:2*a},{adCount:6,spacing:3*a}],maxAdCount:8}};h.getSizing=function(){return{}};
function Aa(a){this.h=a}h=Aa.prototype;h.isEnabled=function(){return!0};h.isResponsiveEnabled=function(){return!1};h.getConfigUrl=function(){var a=z(this.h).get(),b=R(a.canonicalUrl).hostname;return U({client:this.h.getAttribute("data-ad-legacy-client"),plah:b,ama_t:"amp",url:a.canonicalUrl})};h.getAttributes=function(){return E({type:"doubleclick","data-slot":this.h.getAttribute("data-slot"),json:this.h.getAttribute("data-json")})};
h.getDefaultAdConstraints=function(){var a=K(this.h).getSize().height;return{initialMinSpacing:a,subsequentMinSpacing:[{adCount:3,spacing:2*a},{adCount:6,spacing:3*a}],maxAdCount:8}};h.getSizing=function(){a:{var a=this.h.getAttribute("data-experiment");try{var b=JSON.parse(a);break a}catch(d){}b=void 0}var c=b;return c?{height:c.height?Number(c.height):250,width:c.width?Number(c.width):void 0}:{}};function Ba(a,b,c,d,e){this.L=a.slice(0);this.B=b;this.U=c;this.m=d;this.G=0;this.R=void 0===e?!1:e}Ba.prototype.run=function(){var a=this;return this.m.isMaxAdCountReached()?fa(function(){return Ca(a)}):Da(this).then(function(b){return b?a.run():Ca(a)})};function Ca(a){return{adsPlaced:a.G,totalAdsOnPage:a.m.getAdCount()}}
function Da(a){var b=a.L.shift();return b?b.placeAd(a.B,a.U,a.m,a.R).then(function(c){return 2==c?(a.m.addAd(b.getAdElement()),a.G++,!0):Da(a)}):(w().info("amp-auto-ads","unable to fulfill ad strategy"),Promise.resolve(!1))};function V(a,b){this.o=a;this.O=b.initialMinSpacing;this.J=b.subsequentMinSpacing.slice(0).sort(function(a,b){return a.adCount-b.adCount});this.S=b.maxAdCount;this.I=Ea(this)}V.prototype.addAd=function(a){this.o.push(a);this.I=Ea(this)};V.prototype.getAdCount=function(){return this.o.length};V.prototype.isMaxAdCountReached=function(){return this.getAdCount()>=this.S};V.prototype.isTooNearAnAd=function(a){return Fa(this,a,0)};
function Fa(a,b,c){return c>=a.o.length?Promise.resolve(!1):Ga(b,a.o[c]).then(function(d){return d<a.I?!0:Fa(a,b,c+1)})}function Ga(a,b){return C(b,"resources").getElementLayoutBox(b).then(function(b){return a>=b.top&&a<=b.bottom?0:Math.min(Math.abs(a-b.top),Math.abs(a-b.bottom))})}function Ea(a){for(var b=a.getAdCount(),c=a.O,d=0;d<a.J.length;d++){var e=a.J[d];e.adCount<=b&&(c=e.spacing)}return c}
function Ha(a){return[].slice.call(a.getRootNode().getElementsByTagName("AMP-AD")).filter(function(a){return a.parentElement&&"AMP-STICKY-AD"==a.parentElement.tagName?!1:!0})}
function Ia(a,b){b=b.adConstraints;if(!b)return null;var c=K(a).getHeight(),d=Ja(b.initialMinSpacing,c);if(null==d)return w().warn("amp-auto-ads","Invalid initial min spacing"),null;var e=(b.subsequentMinSpacing||[]).map(function(a){var b=a.adCount;if(null==b)return w().warn("amp-auto-ads","No subsequentMinSpacing adCount specified"),null;a=Ja(a.spacing,c);return null==a?(w().warn("amp-auto-ads","Invalid subsequent min spacing"),null):{adCount:b,spacing:a}});return-1!=e.indexOf(null)?null:null==b.maxAdCount?
(w().warn("amp-auto-ads","No maxAdCount specified"),null):{initialMinSpacing:d,subsequentMinSpacing:e,maxAdCount:b.maxAdCount}}function Ja(a,b){if(!a)return null;var c=parseFloat(a);return isNaN(c)||0>c?null:F(a,"px")?c:F(a,"vp")?c*b:null};function Ka(a,b,c){this.ampdoc=a;this.B=b;this.N=c}
Ka.prototype.run=function(){var a;a:{if(a=this.N.optInStatus)for(var b=0;b<a.length;b++)if(2==a[b]){a=!0;break a}a=!1}if(!a)return Promise.resolve(!1);if(0<this.ampdoc.getRootNode().getElementsByTagName("AMP-STICKY-AD").length)return w().warn("amp-auto-ads","exists <amp-sticky-ad>"),Promise.resolve(!1);x(this.ampdoc.win,"extensions").installExtensionForDoc(this.ampdoc,"amp-sticky-ad");a=K(this.ampdoc).getWidth();b=Object.assign({},this.B,E({width:String(a),height:"100"}));a=this.ampdoc.win.document;
b=H(a,"amp-ad",b);a=H(a,"amp-sticky-ad",E({layout:"nodisplay"}));a.appendChild(b);b=this.ampdoc.getBody();b.insertBefore(a,b.firstChild);return Promise.resolve(!0)};function W(a){return AMP.BaseElement.apply(this,arguments)||this}var X=AMP.BaseElement;W.prototype=ba(X.prototype);W.prototype.constructor=W;if(r)r(W,X);else for(var Y in X)if("prototype"!=Y)if(Object.defineProperties){var La=Object.getOwnPropertyDescriptor(X,Y);La&&Object.defineProperty(W,Y,La)}else W[Y]=X[Y];W.V=X.prototype;
W.prototype.buildCallback=function(){var a=this;w().assert(S(this.win,"amp-auto-ads"),"Experiment is off");var b=this.element.getAttribute("type");w().assert(b,"Missing type attribute");var c=ya(b,this.element);w().assert(c,"No AdNetworkConfig for type: "+b);if(c.isEnabled(this.win)){var d=this.getAmpDoc();x(this.win,"extensions").installExtensionForDoc(d,"amp-ad");var e=C(this.getAmpDoc(),"viewer"),f=e.whenFirstVisible();f.then(function(){return Ma(a,c.getConfigUrl())}).then(function(b){if(b){var e=
b.noConfigReason;if(e)a.user().warn("amp-auto-ads",e);else{var f=sa(d,b),g=Object.assign(c.getAttributes(),L(b)),q=c.getSizing(),n=Ia(d,b)||c.getDefaultAdConstraints();n=new V(Ha(d),n);(new Ba(f,g,q,n,c.isResponsiveEnabled(a.win))).run();(new Ka(d,g,b)).run()}}})}};W.prototype.isLayoutSupported=function(){return!0};
function Ma(a,b){var c={mode:"cors",method:"GET",credentials:"omit",requireAmpResponseSourceOrigin:!1};return x(a.win,"xhr").fetchJson(b,c).then(function(a){return a.json()}).catch(function(b){a.user().error("amp-auto-ads","amp-auto-ads config xhr failed: "+b);return null})}(function(a){a.registerElement("amp-auto-ads",W)})(self.AMP);
})});
//# sourceMappingURL=amp-auto-ads-0.1.js.map

